#!/bin/bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Shortcuts
alias p="cd ~/projects"
alias f="open ."
alias h="history"
alias j="jobs"
alias g="git"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

# Always use color output for `ls`
alias ls="command ls ${colorflag}"

# List Shortcuts
alias l="ls -F ${colorflag}"
alias ll="ls -lFh ${colorflag}"
alias la="ls -AF ${colorflag}"
alias al="ls -lAFh ${colorflag}"
alias lsd="ls -l ${colorflag} | grep --color=never '^d'"

# Enable aliases to be sudo’ed
alias sudo='sudo '

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

set bell-style visible

export TERM=xterm-256color

# emacs the default editor
export EDITOR="emacs"
# export EDITOR="emacsclient -c"

# alias eboot="emacs --daemon"
# alias ekill="emacsclient -e '(kill-emacs)'"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=5000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Append to the history file, don't overwrite
shopt -s histappend

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# Create a new directory and enter it
function mkd() {
  mkdir -p "$@" && cd "$@"
}

# `e` with no arguments opens the current directory in $EDITOR,
# otherwise opens the given location
function e() {
  if [ $# -eq 0 ]; then
    $EDITOR .
  else
    $EDITOR "$@"
  fi
}

# search history for a single keyword
function hs() {
  history | grep $1
}

# add '~/.rbenv' if present and init
if [ -d "$HOME/.rbenv/bin" ] ; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# add '~/local/bin' if present
if [ -d "$HOME/local/bin" ] ; then
  export PATH="$HOME/local/bin:$PATH"
fi

# add '~/.npm-packages/bin' if present
if [ -d "$HOME/.npm-packages/bin" ] ; then
  export PATH="$HOME/.npm-packages/bin:$PATH"
fi

# source '~/.nvm/nvm.sh' if present
if [ -d "$HOME/.nvm" ] ; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
fi

# set a colorful prompt... I always use a 256 color term anyway
LT_GRN="\033[38;5;36m"
DK_GRY="\033[38;5;244m"
LT_GRY="\033[38;5;254m"

export PS1="\[$DK_GRY\]in \w\n\[$LT_GRN\]$ \[\e[39m\]"
